# Generated by Django 3.2.7 on 2022-05-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=0, verbose_name='budget'),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.CharField(default='N', max_length=1255, verbose_name='crew'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.CharField(default='N', max_length=1255, verbose_name='production_companies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.CharField(default='N', max_length=1255, verbose_name='production_countries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(default=0, verbose_name='revenue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_language',
            field=models.CharField(default='en', max_length=1255, verbose_name='spoken_language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(default='Released', max_length=255, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='vote_count'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(max_length=1255, verbose_name='cast'),
        ),
    ]
