# Generated by Django 3.2.7 on 2022-05-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20220525_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
