# Generated by Django 3.2.7 on 2022-05-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_remove_movie_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
    ]
