# Generated by Django 3.2.7 on 2022-05-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0010_watched_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liked_videos',
            new_name='Liked_movies',
        ),
        migrations.RenameModel(
            old_name='Watched_videos',
            new_name='Searched_movies',
        ),
        migrations.RenameField(
            model_name='searched_movies',
            old_name='watched',
            new_name='searched',
        ),
        migrations.CreateModel(
            name='Watched_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.movie')),
            ],
        ),
    ]
