# Generated by Django 3.2.7 on 2022-05-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_auto_20220527_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_movies',
            fields=[
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommend.movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='searched_movies',
            name='id',
        ),
        migrations.RemoveField(
            model_name='searched_movies',
            name='searched',
        ),
        migrations.RemoveField(
            model_name='watched_movies',
            name='id',
        ),
        migrations.RemoveField(
            model_name='watched_movies',
            name='watched',
        ),
        migrations.AlterField(
            model_name='searched_movies',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommend.movie'),
        ),
        migrations.AlterField(
            model_name='watched_movies',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommend.movie'),
        ),
    ]
