# Generated by Django 3.2.7 on 2022-05-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0015_auto_20220527_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked_movies',
            name='id',
        ),
        migrations.AlterField(
            model_name='liked_movies',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommend.movie'),
        ),
    ]
