# Generated by Django 3.2.7 on 2022-05-28 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0017_auto_20220528_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked_movies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved_movies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searched_movies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watched_movies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liked_movies',
            name='movie_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommend.movie'),
        ),
        migrations.AlterField(
            model_name='saved_movies',
            name='movie_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommend.movie'),
        ),
        migrations.AlterField(
            model_name='searched_movies',
            name='movie_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommend.movie'),
        ),
        migrations.AlterField(
            model_name='watched_movies',
            name='movie_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommend.movie'),
        ),
    ]
